### ISSUE TITLE
quick start

### ISSUE THREAD

**Issue by anomal3** [Agasper/Warden.NetRpc#1]
Добрый вечер Александр. А Wiki будет с примером?
Хочется быстрый старт увидеть)

Новая библиотека новые возможности?

**Comment by Agasper** [comment]
Добрый день, обязательно будет с примерами, но пока к сожалению не хватает времени

**Comment by anomal3** [comment]
Я ждал и я жду. Не забывайте пожалуйста про Wiki

**Comment by Agasper** [comment]
Если вам нужен Rpc на C# вы можете воспользоваться GRPC [https://grpc.io/](https://grpc.io/)

**Comment by anomal3** [comment]
> Если вам нужен Rpc на C# вы можете воспользоваться GRPC https://grpc.io/

Ненене))) gRPC не нужен) хочу Вашу библиотеку)
У Вас подход для людей, и мне ближе такой код.

Я ещё с AgasperPatcher заметил
![Agasper](https://user-images.githubusercontent.com/12729713/108389264-f0414600-7228-11eb-8ad8-40fd378fa825.png)

Читабельный формат для людей 👍 

А хоть и старая библиотека но всё же TCP Ваш ну оочень прост в использовании.

Так что буду ждать ВиКи

**Comment by Agasper** [comment]
Я буду с вами честен, не думаю что документация появится в ближайшее время, т.к. библиотека в стадии разработки и часто меняется и пока предназначена для внутреннего использования в компании
